name: Go
on: [push]
jobs:

  spectralops:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: curl -L spectralops.io/get | sudo sh
      - name: Scan
        run: spectral run
        
  validator:
    name: Checks Validators
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1    
    
    - name: Checks validator
      run: |
        make checks-validator

  test:
    name: Code Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1   
    - name: Run tests
      run: |
        make test